import clsx from "clsx";
import type { Metadata } from "next";
import Footer from "./_components/footer";
import Header from "./_components/header";
import { plus_jakarta_sans } from "./_lib/fonts";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={clsx(
          plus_jakarta_sans.className,
          "flex h-screen flex-col bg-background text-xs sm:text-sm",
        )}
      >
        <Providers>
          <Header />
          {props.children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
